### ISSUE TITLE
no documentation

### ISSUE THREAD

**Issue by francescogosce** [itsravenous/rv-iscroll#4]
there is no documentation :|

**Comment by yogaraptor** [comment]
Did you check the [README](https://github.com/itsravenous/rv-iscroll/blob/master/README.md)? It's displayed on the [root page](https://github.com/itsravenous/rv-iscroll) of the project, as with all GitHub projects.

**Comment by francescogosce** [comment]
there is no documentation about how to use it or examples

**Comment by yogaraptor** [comment]
I'll grant you there's no link to the demo (or how to run the demo), but that's not quite the same thing as "no documentation" - the README contains all the information you need to use the element once installed. I've added instructions on installing the component via Bower and on running the demo if you just want to try it out from this repo.
